/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

//import javax.swing.JOptionPane;

public class ViewEntrada extends javax.swing.JFrame {

    /**
     * Creates new form ViewCadastro
     */
    public ViewEntrada() {
        initComponents();
    }
//    public boolean Br;
//    public boolean Us;
//    public boolean Es;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tela = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnCadastro = new javax.swing.JButton();
        btnSobre = new javax.swing.JButton();
        btnIngles = new javax.swing.JButton();
        btnEspanol = new javax.swing.JButton();
        btnBR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/EntradaBr.jpeg"))); // NOI18N
        getContentPane().add(Tela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnLogin.setText("jButton1");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 263, 320, 70));

        btnCadastro.setText("jButton2");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 353, 320, 70));

        btnSobre.setText("jButton3");
        getContentPane().add(btnSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 433, 320, 70));

        btnIngles.setText("jButton4");
        btnIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInglesActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngles, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 623, -1, 80));

        btnEspanol.setText("jButton5");
        btnEspanol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspanolActionPerformed(evt);
            }
        });
        getContentPane().add(btnEspanol, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 623, 60, 80));

        btnBR.setText("jButton6");
        btnBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBRActionPerformed(evt);
            }
        });
        getContentPane().add(btnBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 623, 60, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    new ViewLogin().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed

//        if (Br = true) {
//           ViewCadastro cadastro = new ViewCadastro(Br);
//           
//        this.dispose();  
//        }
        new ViewCadastro().setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInglesActionPerformed
        //Modifica a imagem da Tela principal
       Tela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/EntradaUS.jpeg")));
       
//       Br = false;
//       Us = true;
//       Es = false;
       
    }//GEN-LAST:event_btnInglesActionPerformed

    private void btnEspanolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspanolActionPerformed

         //Modifica a imagem da Tela principal
       Tela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/EntradaES.jpeg")));
        
    }//GEN-LAST:event_btnEspanolActionPerformed

    private void btnBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBRActionPerformed

     //Modifica a imagem da Tela principal
       Tela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/EntradaBr.jpeg")));

    }//GEN-LAST:event_btnBRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEntrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tela;
    private javax.swing.JButton btnBR;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnEspanol;
    private javax.swing.JButton btnIngles;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSobre;
    // End of variables declaration//GEN-END:variables
}
